
baseURL = "http://edmarferreira.com"
title = "Edmar Ferreira"
themesDir = "themes"
theme = "hugo-winston-theme"

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 10
  [languages.pt]
    contentDir = 'content/pt'
    languageName = 'Português'
    weight = 20

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 5

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@edmarferreira"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false 
  addFrame = true
  addDot = true
